name: config-github-action
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Teste
        uses: actions/checkout@v4
      - name: Teste1
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: npm install
      - run: node app.js

